# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 162c7a16ebcd23f032f6dd0997a62e56ad6393434499408c3c9cc416549fa26716ac2f2340805fb7ef17836e967a2c78995c07a219b4e7017d207a23f1ab7bbc

test:
  secret_key_base: 772f6a45ffb32290228b531eaa2623051043107448a9a3c514da52d698787e576e05831db86e665fdf80c0e8d5fdc3c3eca55d16471b0e864203e447afca8664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
